export const getInitialCards = (userId: string) => [
  {
    title: "Coffee House",
    subtitle: "Fresh coffee every day",
    description: "Local coffee shop and bakery",
    phone: "0524720544",
    email: "coffee@cards.com",
    web: "https://example.com/coffee",
    image: {
      url: "https://picsum.photos/200/300",
      alt: "coffee house",
    },
    address: {
      state: "IL",
      country: "Israel",
      city: "Tel Aviv",
      street: "Dizengoff",
      houseNumber: 10,
      zip: "61000",
    },
    userId,
    bizNumber: 100001,
    likes: [],
  },
  {
    title: "Tech Solutions",
    subtitle: "IT services for businesses",
    description: "Computers, networks and support",
    phone: "0524720544",
    email: "tech@cards.com",
    web: "https://example.com/tech",
    image: {
      url: "https://picsum.photos/200/301",
      alt: "tech solutions",
    },
    address: {
      state: "IL",
      country: "Israel",
      city: "Ramat Gan",
      street: "Bialik",
      houseNumber: 20,
      zip: "52000",
    },
    userId,
    bizNumber: 100002,
    likes: [],
  },
  {
    title: "Design Studio",
    subtitle: "Creative design services",
    description: "Branding and digital design studio",
    phone: "0524720544",
    email: "design@cards.com",
    web: "https://example.com/design",
    image: {
      url: "https://picsum.photos/200/302",
      alt: "design studio",
    },
    address: {
      state: "IL",
      country: "Israel",
      city: "Haifa",
      street: "Haneviim",
      houseNumber: 30,
      zip: "33000",
    },
    userId,
    bizNumber: 100003,
    likes: [],
  },
];
